name: avatar-img
on:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  avatar:
    name: avatar-img
    runs-on: ubuntu-20.04
    steps:
      - name: clone codes
        env:
          CODE: ${{ secrets.CODING_REPO_PREFIX }}/avatar/code.git
          BACHELOR: ${{ secrets.CODING_REPO_PREFIX }}/avatar/bachelor.git
          MASTER: ${{ secrets.CODING_REPO_PREFIX }}/avatar/master.git
          DOCTOR: ${{ secrets.CODING_REPO_PREFIX }}/avatar/doctor.git
        run: |
          git clone $CODE
          git clone $BACHELOR
          git clone $MASTER
          git clone $DOCTOR
          cd code
          cat down_from_db.py
      - name: run codes
        run: |
          cd code
          python3 down_from_db.py
      - name: push
        env:
          BACHELOR: ${{ secrets.CODING_REPO_PREFIX }}/avatar/bachelor.git
          MASTER: ${{ secrets.CODING_REPO_PREFIX }}/avatar/master.git
          DOCTOR: ${{ secrets.CODING_REPO_PREFIX }}/avatar/doctor.git
        run: |
          git config --global user.name "SunYufei"
          git config --global user.email "sunyufei963@qq.com"
          cd bachelor
          rm -rf .git/
          git init
          git remote add origin $REPO_IMG
          git add .
          git commit -m "Pushed by GitHub Actions"
          git push -u origin master -f
          cd ../master
          rm -rf .git/
          git init
          git remote add origin $REPO_IMG
          git add .
          git commit -m "Pushed by GitHub Actions"
          git push -u origin master -f
          cd ../doctor
          rm -rf .git/
          git init
          git remote add origin $REPO_IMG
          git add .
          git commit -m "Pushed by GitHub Actions"
          git push -u origin master -f
