name: avatar-img
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  avatar:
    name: avatar-img
    runs-on: ubuntu-20.04
    steps:
      - name: clone codes
        env:
          REPO_CODE: ${{ secrets.CODING_REPO_PREFIX }}/avatar/code.git
          REPO_IMG: ${{ secrets.CODING_REPO_PREFIX }}/avatar/image.git
        run: |
          git clone $REPO_CODE
          git clone $REPO_IMG
          cd code
          cat down_from_db.py
      - name: run codes
        run: |
          cd code
          python3 down_from_db.py
      - name: push
        env:
          REPO_IMG: ${{ secrets.CODING_REPO_PREFIX }}/avatar/image.git
        run: |
          git config --global user.name "SunYufei"
          git config --global user.email "sunyufei963@qq.com"
          cd image
          rm -rf .git/
          git init
          git remote add origin $REPO_IMG
          git add .
          git commit -m "Pushed by GitHub Actions"
          git push -u origin master -f