name: avatar
on:
  push:
    branches:
      - some
  schedule:
    - cron: '0 * * * *'

jobs:
  avatar:
    name: avatar
    runs-on: ubuntu-20.04
    steps:
      - name: clone codes
        env:
          REPO_CODE: ${{ secrets.CODING_REPO_PREFIX }}/avatar/code.git
        run: |
          git clone $REPO_CODE
          cd code
          cat run.py
      - name: run codes
        run: |
          cd code
          python3 run.py
      - name: push
        run: |
          git config --global user.name "SunYufei"
          git config --global user.email "sunyufei963@qq.com"
          cd code
          git add .
          git commit -m "Pushed by GitHub Actions"
          git push
