name: JD-Sign
on:
  push:
  schedule:
    - cron: '5 16 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: run codes
        run: |
          cd jd-sign
          npm install
          node app.js
          cat result.txt
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
