name: rclone
on:
  push:
    branches: 
      - some

jobs:
  transfer:
    runs-on: ubuntu-latest
    steps:
      - uses: NiceLabs/rclone-action@master
        with:
          # args: copy --update --verbose GoogleDrive:/Video OneDrive:/
          config: ${{ secrets.RCLONE_CONF }}
      - name: rclone move
        run: |
          rclone move --delete-empty-src-dirs -v GoogleDrive:/ OneDrive:/Videos/
